TestSite/Controllers/ContactController.cs
using System;
using System.Collections.Generic;
using System.Web.Mvc;
using System.Web.WebPages;
using Hangfire;
using TestSite.Infrastructure;
using TestSite.Models;
using TestSite.Persistence;
using TestSite.Scripts;

namespace TestSite.Controllers
{
    public class ContactController : Controller
    {
        // GET: Contact
        public ActionResult Index()
        {
            User user = new User();
            if (Session["User"] != null)
            {
                user = (User)Session["User"];
            }
            if (user.Mail == null)
            {
                return Redirect("/User/Login");
            }
            UnitOfWork unit = new UnitOfWork(new PlutoContext());
            IEnumerable<Contact> contactList = unit.Contacts.GetAll();
            Session["Contacts"] = contactList;
            return View();
        }

        public ActionResult Funktion(int id, string funktion)
        {
            User user = new User();
            if (Session["User"] != null)
            {
                user = (User)Session["User"];
            }
            if (user != null && user.Mail == null)
            {
                return Redirect("/User/Login");
            }
            SystemMessage message = new SystemMessage();
            switch (funktion)
            {
                case "Melden":
                {
                    UnitOfWork unit = new UnitOfWork(new PlutoContext());
                    BackgroundJob.Enqueue(() => message.NewAction("KONTAKT GEMELDET",
                        "Der Kontakt mit der ID: " + id +
                        ", wurde soeben von"+user.Firstname+" "+user.Lastname +" gemeldet.  //" + DateTime.Now.ToString()));

                    unit.Contacts.ChangeStatus(id, 2);
                    return Redirect("/Contact/Index");
                }
                case "Sperren":
                {
                    if (user.Roles != "Admin" && user.Roles != "Support") return Redirect("/Contact/Index");
                    UnitOfWork unit = new UnitOfWork(new PlutoContext());
                    unit.Contacts.ChangeStatus(id, 1);
                    return Redirect("/Contact/Index");
                }
                case "Entsperren":
                {
                    if (user.Roles != "Admin") return Redirect("/Contact/Index");
                    UnitOfWork unit = new UnitOfWork(new PlutoContext());
                    unit.Contacts.ChangeStatus(id, 0);
                    unit.Complete();
                    return Redirect("/Contact/Index");
                }
                case "Löschen":
                {
                    if (user.Roles != "Admin") return Redirect("/Contact/Index");
                    UnitOfWork unit = new UnitOfWork(new PlutoContext());
                    unit.Contacts.ChangeStatus(id, 3);
                    return Redirect("/Contact/Index");
                }
                case "Reaktivieren":
                {
                    if (user.Roles != "Admin") return Redirect("/Contact/Index");
                    UnitOfWork unit = new UnitOfWork(new PlutoContext());
                    unit.Contacts.ChangeStatus(id, 0);
                    return Redirect("/Contact/Index");
                }
            }
            if (funktion != "Bearbeiten") return Redirect("/Contact/Index");
            {
                UnitOfWork unit = new UnitOfWork(new PlutoContext());
                Contact contact = unit.Contacts.Get(id);
                if (contact.CreateById == user.Id || user.Roles == "Admin" || user.Roles == "Support")
                {
                    return Redirect("/Contact/EditContact?Id=" + id);
                }
            }
            return Redirect("/Contact/Index");
        }

        public ActionResult EditContact(string id)
        {
            User user = new User();
            if (Session["User"] != null)
            {
                user = (User) Session["User"];
            }
            if (user.Mail == null)
            {
                return Redirect("/User/Login");
            }
            if (id == null)
            {
                return Redirect("/Contact/Index");
            }
            UnitOfWork unit = new UnitOfWork(new PlutoContext());
            Contact contact = unit.Contacts.Get(id.AsInt());
            if (contact.CreateById != user.Id)
            {
                return Redirect("/User/Login");
            }
            ViewData["EditContact"] = contact;
            return View();
        }

        public ActionResult SaveContact(Contact contact)
        {
            User user = new User();
            if (Session["User"] != null)
            {
                user = (User)Session["User"];
            }
            if (user != null && user.Mail == null)
            {
                return Redirect("/User/Login");
            }
            UnitOfWork unit = new UnitOfWork(new PlutoContext());
            unit.Contacts.Add(contact);
            unit.Complete();
            return Redirect("/Contact/Index");
        }

        public ActionResult Archiv()
        {
            User user = new User();
            if (Session["User"] != null)
            {
                user = (User) Session["User"];
            }
            if (user != null && user.Mail == null)
            {
                return Redirect("/User/Login");
            }
            if (user != null && user.Roles == "User")
            {
                return Redirect("/Contact/Index");
            }

            UnitOfWork unit = new UnitOfWork(new PlutoContext());
            IEnumerable<Contact> contactList = unit.Contacts.GetAll();
            Session["ContactsArchiv"] = contactList;

            return View("Archiv");
        }

        public ActionResult NewContact()
        {
            User user = new User();
            if (Session["User"] != null)
            {
                user = (User)Session["User"];
            }
            if (user != null && user.Mail == null)
            {
                return Redirect("/User/Login");
            }
            return View();
        }

        public ActionResult SaveNewContact(Contact contact)
        {
            User user = new User();
            if (Session["User"] != null)
            {
                user = (User)Session["User"];
            }
            if (user != null && user.Mail == null)
            {
                return Redirect("/User/Login");
            }
            UnitOfWork unit = new UnitOfWork(new PlutoContext());
            contact.Status = 0;
            unit.Contacts.Add(contact);
            unit.Complete();
            return Redirect("/Contact/Index");
        }
    }
}

TestSite/Controllers/MailController.cs
using System;
using System.Globalization;
using System.Web.Mvc;
using System.Web.WebPages;
using TestSite.Infrastructure;
using TestSite.Models;
using TestSite.Persistence;

namespace TestSite.Controllers
{
    public class MailController : Controller
    {
        // GET: Mail
        public ActionResult Index()
        {
            User user = new User();
            if (Session["User"] != null)
            {
                user = (User) Session["User"];
            }
            if (user.Mail == null)
            {
                return Redirect("/User/Login");
            }
            return View();
        }

        public ActionResult NewMail()
        {
            User user = new User();
            if (Session["User"] != null)
            {
                user = (User)Session["User"];
            }
            if (user.Mail == null)
            {
                return Redirect("/User/Login");
            }
            return View();
        }

        public ActionResult SaveMail(Mail mail)
        {
            User user = new User();
            if (Session["User"] != null)
            {
                user = (User)Session["User"];
            }
            if (user.Mail == null)
            {
                return Redirect("/User/Login");
            }
            mail.Date = DateTime.Now.ToString(CultureInfo.InvariantCulture);
            mail.Delete = "false";
            UnitOfWork unit = new UnitOfWork(new PlutoContext());
            try
            {
                user = unit.Users.FindMail(mail.ToId);
                mail.ToId = user.Id.ToString();
            }
            catch (Exception)
            {
                // ignored
            }
            unit.Mails.Add(mail);
            unit.Complete();
            return Redirect("Index");
        }

        public ActionResult ReadMail(string id)
        {
            User user = new User();
            if (Session["User"] != null)
            {
                user = (User)Session["User"];
            }
            if (user.Mail == null)
            {
                return Redirect("/User/Login");
            }
            if (id == null)
            {
                id = (string) Session["ThisMailId"];
                Session["ThisMailId"] = null;
            }
            UnitOfWork unit = new UnitOfWork(new PlutoContext());
            Mail mail = unit.Mails.Get(id.AsInt());
            mail.IsRead = "true";
            unit.Complete();
            unit.Mails.Add(mail);
            unit.Complete();
            Session["actuallMail"] = mail;
            return View();
        }

        public ActionResult SaveAnswerMail(Mail mail)
        {
            User user = new User();
            if (Session["User"] != null)
            {
                user = (User)Session["User"];
            }
            if (user.Mail == null)
            {
                return Redirect("/User/Login");
            }
            mail.Delete = "false";
            mail.Date = DateTime.Now.ToString(CultureInfo.InvariantCulture);

            UnitOfWork unit = new UnitOfWork(new PlutoContext());
            unit.Mails.Add(mail);
            unit.Complete();

            Session["ThisMailId"] = mail.TopId;
            return Redirect("/Mail/ReadMail");
        }

        public ActionResult DeleteMail(string id)
        {
            User user = new User();
            if (Session["User"] != null)
            {
                user = (User)Session["User"];
            }
            if (user.Mail == null)
            {
                return Redirect("/User/Login");
            }
            UnitOfWork unit = new UnitOfWork(new PlutoContext());
            Mail mail = unit.Mails.Get(id.AsInt());

            mail.Delete = "true";
            unit.Mails.Add(mail);
            unit.Complete();

            return Redirect("/Mail/Index");
        }

        public ActionResult Intern()
        {
            User user = new User();
            if (Session["User"] != null)
            {
                user = (User)Session["User"];
            }
            if (user.Mail == null)
            {
                return Redirect("/User/Login");
            }
            if (user.Roles == "Admin" || user.Roles == "Support")
            {
                return View();
            }
            return Redirect("/Mail/Index");
        }

        public ActionResult Ticket()
        {
            User user = new User();
            if (Session["User"] != null)
            {
                user = (User) Session["User"];
            }
            if (user.Mail == null)
            {
                return Redirect("/Forum/Index");
            }
            return View();
        }
    }
}

TestSite/Views/Shared/_Layout.cshtml
@using System.Collections.ObjectModel
@using TestSite.Infrastructure
@using TestSite.Models
@using TestSite.Persistence
@using TestSite.Scripts
@{
    User actualluser = new User();
    if (Session["User"] != null)
    {
        actualluser = (User) Session["User"];
    }
    string username = actualluser.Firstname;

    string mailstatus = "Mails";
    UnitOfWork unit = new UnitOfWork(new PlutoContext());
    IEnumerable<Mail> mails = unit.Mails.GetAll();
    int mailcounter = 0;
    int mailinterncounter = 0;
    string internmailstatus = "Intern";
    foreach (Mail m in mails)
    {
        if (m.ToId.AsInt() == actualluser.Id && m.IsRead == "false")
        {
            mailcounter++;
        }
    }
    if (mailcounter != 0)
    {
        mailstatus = "Mails [" + mailcounter + "]";
    }

    foreach (Mail m in mails)
    {
        if (m.Type == "system" && m.Delete == "false")
        {
            mailinterncounter++;
        }
    }
    if (mailinterncounter != 0)
    {
        internmailstatus = "Intern [" + mailinterncounter + "]";
    }
    ObservableCollection<Mail> broadmail = new ObservableCollection<Mail>();
    foreach (Mail m in mails)
    {
        if (m.Type == "broadcast")
        {
            broadmail.Add(m);
        }
    }
    Counter count = new Counter();
    int users = count.User();
    int topics = count.Topic();
    int articles = count.Article();
    string broadcaster = broadmail[broadmail.Count - 1].Message;
}

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Kontakt Liste</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
<div class="navbar navbar-default navbar-fixed-top">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            @Html.ActionLink("Kontakt Liste", "Index", "Home", new {area = ""}, new {@class = "navbar-brand"})
        </div>
        <div class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
                @if (actualluser.Mail != null)
                {
                    if (actualluser.Roles == "Admin")
                    {
                        <li><a href="/User/Profiles?id=@actualluser.Id">✧@actualluser.Firstname✧</a></li>
                    }
                    if (actualluser.Roles == "Support")
                    {
                        <li><a href="/User/Profiles?id=@actualluser.Id">⚪@actualluser.Firstname⚪</a></li>
                        
                    }
                    if (actualluser.Roles == "User")
                    {
                        <li><a href="/User/Profiles?id=@actualluser.Id">||@actualluser.Firstname||</a></li>
                    }

                    <li><a href="/Contact/Index">Kontaktbuch</a></li>
                    <li><a href="/Mail/Index">@mailstatus</a></li>
                    if (actualluser.Roles == "User")
                    {
                        <li><a href="/Mail/Ticket">Ticket</a></li>
                    }
                }
                <li>@Html.ActionLink("Mitglieder", "UserList", "User")</li>
                <li>@Html.ActionLink("Forum", "Index", "Forum")</li>


                @if (actualluser.Roles == "Admin" || actualluser.Roles == "Support")
                {
                    <li>@Html.ActionLink(internmailstatus, "Intern", "Mail")</li>
                    <li> @Html.ActionLink("Verwaltung", "RoleManager", "User")</li>
                }

            </ul>
            @Html.Partial("_LoginPartial")
        </div>
    </div>
    <div class="well well-sm" style="border-radius: 20px; width: 700px; text-align: center; margin: auto;">@broadcaster</div>

</div>
<div class="container body-content">
    <br/><br/><br/><br/>
    @RenderBody()
    <hr/>
</div><br/><br/><br/>

<footer style="position: fixed; bottom: 0; width: 100%; background-color: white; border-top: 2px solid black">
    <p style="width: 100%">
        <ul style="margin-left: 20px; float: left; display: inline; list-style: none; text-align: left">
            <li>Wir haben <span style="font-weight: bold">@users</span> registrierte Mitglieder.</li>
            <li>Die in <span style="font-weight: bold">@topics</span> Topics,</li>
            <li><span style="font-weight: bold">@articles</span> Artikel erstellt haben.</li>
        </ul>

        <ul style="float: right; text-align: right; list-style: none; display: inline; margin-right: 60px;">
            <li>&copy; @DateTime.Now.Year - Kontakt Liste </li>
            <li>@Html.ActionLink("Kontakt", "Contact", "Home")</li>
            <li>@DateTime.Now.ToShortDateString()</li>
        </ul>
    </p>

</footer>
@Scripts.Render("~/bundles/jquery")
@Scripts.Render("~/bundles/bootstrap")
@RenderSection("scripts", false)
</body>
</html>